### ISSUE TITLE
Support Non-Nullability

### ISSUE THREAD

**Issue by kostaa** [brianegan/reselect_dart#8]
Is this library still maintained?
Any plans Non-Nullability?

**Comment by brianegan** [comment]
Sure, happy to update when the memoize dependency is published!

**Comment by kostaa** [comment]
Hi 'memoize' library has been upgraded and published to pub.

**Comment by brianegan** [comment]
I understand the desire to upgrade, but again please have patience. The
package has not been shipped to pub.


https://github.com/wrike/memoize_dart/issues/11

https://pub.dev/packages/memoize/versions

**Comment by kostaa** [comment]
Apologies looks like I have jumped the gun.

**Comment by missvalentinep** [comment]
@brianegan @kostaa the package has been published to pub! Terribly sorry for the long wait

**Comment by brianegan** [comment]
@missvalentinep No worries at all. Thanks for taking the time to sort out the issues and publish the new version :)

**Comment by brianegan** [comment]
Published 0.5.0
